apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsimages.jenkins
spec:
  group: jenkins
  names:
    kind: JenkinsImage
    listKind: JenkinsImageList
    plural: jenkinsimages
    singular: jenkinsimage
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha2
    served: true
    storage: true
